version: '2.0'

services:

  users-service:
    container_name: user-service
    build:
      context: ./userService
      dockerfile: Dockerfile-dev
    volumes:
      - './userService:/usr/src/app'
    ports:
      - 5001:5000
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - APP_SETTINGS=developmentDocker
      - CONSUL_HOST=172.17.0.1
      - CONSUL_PORT=8500
  mongodb:
    container_name: userservice-mongo
    image: mongo
    ports:
      - "27017:27017"
